# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 01:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None)),
                ('peer_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('peer_port', models.IntegerField(blank=True, null=True)),
                ('qos', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('mountpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('clean_session', models.NullBooleanField()),
                ('retain', models.NullBooleanField()),
            ],
        ),
    ]
