# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqttaction',
            name='topics',
        ),
    ]
